# Generated by Django 4.1 on 2022-09-25 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('matricula', models.OneToOneField(max_length=14, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateTimeField()),
                ('sexo', models.CharField(max_length=1, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=8, unique=True)),
                ('telefone', models.CharField(max_length=16)),
                ('estado_civil', models.CharField(max_length=20)),
                ('naturalidade', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
