# Generated by Django 4.1 on 2022-09-29 13:09

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('matricula', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Homem Cis'), ('M', 'Mulher Cis'), ('K', 'Homem Trans'), ('W', 'Mulher Trans')], max_length=1)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('rg', models.CharField(max_length=8, unique=True)),
                ('telefone', models.CharField(max_length=16)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro'), ('C', 'Casado'), ('V', 'Viúvo'), ('H', 'Separado'), ('D', 'Divorciado'), ('U', 'União Estável')], max_length=1)),
                ('naturalidade', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=130)),
                ('password', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('nome_egresso', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField()),
                ('usuario_responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pai', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=160)),
            ],
        ),
    ]
