# Generated by Django 4.1 on 2022-12-13 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunos',
            options={'permissions': (('views_alunos', 'pode ver views do grupo aluno'),)},
        ),
        migrations.AlterModelOptions(
            name='egresso',
            options={'permissions': (('views_egresso', 'pode ver views do grupo egresso'),)},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'permissions': (('views_pais', 'pode ver views do grupo pais'),)},
        ),
        migrations.AddField(
            model_name='alunos',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='egresso',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
