# Generated by Django 4.1 on 2022-09-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='pais_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudante.alunos'),
        ),
    ]
