# Generated by Django 4.1 on 2022-09-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0002_pais_pais_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='pais_id',
        ),
    ]
