# Generated by Django 4.1 on 2022-09-28 19:10

import cursos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=150)),
                ('quantidade_vagas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=150)),
                ('quantidade_vagas', models.PositiveIntegerField(blank=True, default=0)),
                ('quantidade_creditos', models.PositiveIntegerField(blank=True, default=0)),
                ('carga_horaria', models.CharField(max_length=150)),
                ('conteudo_ministrado', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_disciplina', models.ForeignKey(max_length=14, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_aula', models.DateField()),
                ('titulo_dias_aula', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_disciplina', cursos.models.MinMaxFloat()),
            ],
        ),
    ]
