# Generated by Django 4.1 on 2022-10-07 23:16

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=150)),
                ('quantidade_vagas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=150)),
                ('quantidade_vagas', models.PositiveIntegerField(blank=True, default=0)),
                ('quantidade_creditos', models.PositiveIntegerField(blank=True, default=0)),
                ('tipo_disciplina', models.CharField(blank=True, choices=[('OB', 'Obrigatória'), ('OP', 'Optativa')], max_length=150)),
                ('carga_horaria', models.CharField(max_length=150)),
                ('conteudo_ministrado', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aula', models.DateField()),
                ('titulo_dias_aula', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_disciplina', cursos.models.MinMaxFloat()),
            ],
        ),
    ]
