# Generated by Django 4.1 on 2022-12-10 23:57

import cpf_field.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('endereco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=130)),
                ('password', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=16)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('rg', models.CharField(blank=True, max_length=13, unique=True)),
                ('data_nascimento', models.DateField(blank=True, max_length=8, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Homem Cis'), ('M', 'Mulher Cis'), ('K', 'Homem Trans'), ('W', 'Mulher Trans')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viúvo(a)'), ('H', 'Separado(a)'), ('D', 'Divorciado(a)'), ('U', 'União Estável')], max_length=1)),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
                ('carga_horaria', models.IntegerField(null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.curso')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endereco.endereco')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=130)),
                ('password', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=16)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('rg', models.CharField(blank=True, max_length=13, unique=True)),
                ('data_nascimento', models.DateField(blank=True, max_length=8, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Homem Cis'), ('M', 'Mulher Cis'), ('K', 'Homem Trans'), ('W', 'Mulher Trans')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viúvo(a)'), ('H', 'Separado(a)'), ('D', 'Divorciado(a)'), ('U', 'União Estável')], max_length=1)),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endereco.endereco')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=130)),
                ('password', models.CharField(max_length=160)),
                ('telefone', models.CharField(max_length=16)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('rg', models.CharField(blank=True, max_length=13, unique=True)),
                ('data_nascimento', models.DateField(blank=True, max_length=8, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Homem Cis'), ('M', 'Mulher Cis'), ('K', 'Homem Trans'), ('W', 'Mulher Trans')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('V', 'Viúvo(a)'), ('H', 'Separado(a)'), ('D', 'Divorciado(a)'), ('U', 'União Estável')], max_length=1)),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.curso')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endereco.endereco')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
