# Generated by Django 4.1 on 2022-09-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=130)),
                ('email', models.EmailField(max_length=130)),
                ('senha', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=16)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=13, unique=True)),
                ('data_nascimento', models.DateField(blank=True, max_length=8)),
                ('sexo', models.CharField(blank=True, choices=[('H', 'Homem Cis'), ('M', 'Mulher Cis'), ('K', 'Homem Trans'), ('W', 'Mulher Trans')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Solteiro'), ('C', 'Casado'), ('V', 'Viúvo'), ('H', 'Separado'), ('D', 'Divorciado'), ('U', 'União Estável')], max_length=1)),
                ('naturalidade', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestao.employee')),
            ],
            bases=('gestao.employee',),
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestao.employee')),
            ],
            bases=('gestao.employee',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestao.employee')),
                ('carga_horaria', models.IntegerField(max_length=3, null=True)),
            ],
            bases=('gestao.employee',),
        ),
    ]
