# Generated by Django 4.1 on 2022-12-13 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'permissions': (('views_professor', 'pode ver views do grupo professor'),)},
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='nome',
            field=models.CharField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='nome',
            field=models.CharField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='professor',
            name='carga_horaria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
