# Generated by Django 4.1 on 2022-09-25 00:34

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='carga_horaria',
            field=models.IntegerField(null=True),
        ),
    ]
