# Generated by Django 4.1 on 2022-09-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('cursos', '0001_initial'),
        ('gestao', '0002_alter_employee_cpf_alter_professor_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='curso',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='employee',
            name='endereco',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='endereco.endereco'),
        ),
        migrations.AddField(
            model_name='professor',
            name='cursos',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.curso'),
        ),
    ]
