# Generated by Django 4.1 on 2022-09-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('cursos', '0001_initial'),
        ('gestao', '0003_coordenador_curso_employee_endereco_professor_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='endereco.endereco'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='cursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.curso'),
        ),
    ]
