# Generated by Django 4.1 on 2022-09-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_coordenador_curso_alter_employee_endereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='cursos',
            new_name='curso',
        ),
    ]
