# Generated by Django 4.1 on 2022-09-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_rename_cursos_professor_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='senha',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='employee',
            name='data_nascimento',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
