# Generated by Django 4.1 on 2022-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_rename_senha_employee_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=160),
        ),
    ]
